### ISSUE TITLE
Are there any plans to port this to ciris 2.0.0/cats-effect 3.0.0? 

### ISSUE THREAD

**Issue by jbwheatley** [ovotech/ciris-aiven-kafka#18]
Hello! I'm porting a service to use cats-effect 3 and we are using ciris-aiven-kafka. Is support for ciris 2.0.0 planned in the near future?

**Comment by mwz** [comment]
Hey, would you like to go ahead and make the change yourself?
See https://github.com/ovotech/ciris-aws-secretsmanager/pull/4 for a reference.

**Comment by jbwheatley** [comment]
sure, happy to put together a PR

**Comment by lancewalton** [comment]
Hi. I need this too. I'd be grateful if you would merge Jack's pull request :-)

**Comment by TobiasRoland** [comment]
@rmorais Hey thanks for merging the PR - will there be a dot-release available soon with the changes?

**Comment by rmorais** [comment]
This was release with https://github.com/ovotech/ciris-aiven-kafka/releases/tag/v2.0.0
